### ISSUE TITLE
sa2 battle network dll error

### ISSUE THREAD

**Issue by Tegral** [SonicFreak94/sa2-battle-network#16]
my friend and i followed your instructions to a t and when we load it up it can't find the sa2 battle network dll. we've tried uninstalling and reinstalling. moving the dll around nothing. was hoping you have a fix for it.

**Comment by michael-fadely** [comment]
Are you absolutely certain you installed the **x86** Microsoft Visual C++ 2015 redistributable?

**Comment by Tegral** [comment]
I am yes but (x86) is usually 64 bit whereas (x64) is usually 32 bit.
That's why my program files folder says program files (x86) cause I have a
64 bit is. Should I try getting the other one?

**Comment by michael-fadely** [comment]
You've got that reversed. x86 is 32-bit, x86-64--or x64 for short--is 64-bit. `Program Files (x86)` is the default installation folder for 32-bit applications on 64-bit Windows, although there's nothing stopping installers from putting 64-bit applications in there.

As for the issue at hand: does this happen at all with the mod disabled in the mod manager?

**Comment by Tegral** [comment]
I haven't tried disabling the mod but I think my friend said it did. i'll
give it a shot and get back to you.

**Comment by Tegral** [comment]
no i only get the issue with the mod activated

**Comment by Tegral** [comment]
the exact quote is "Sa2 battle network DLL error - the specified module
could not be found"

**Comment by Tegral** [comment]
so i checked and it never installed that version of vcredist.so i got it
installed and it will load fine now. now when my frined or i adds -connect
and -host we just load up 2 player battle and it works?

**Comment by michael-fadely** [comment]
That's right. You can find more details on that in the Sonic Retro thread.
