### ISSUE TITLE
Music frequently breaks on round start

### ISSUE THREAD

**Issue by michael-fadely** [SonicFreak94/sa2-battle-network#23]
The stage music can start and then quickly stop at the beginning of a round, and it happens regardless of latency. It looks like a bug in the game's code which happens only when the netplay code is running, interestingly. The issue with that is the only variables modified by the netplay code are the game state and player actions, but those aren't touched at this point.

It's straight up calling `StopMusic` when it's not supposed to~~, seemingly because `Pose2PStart_PlayerNum_dupe` isn't -1 when it should be, because that's the only case in which the `BgmStart` objects will call `StopMusic`~~.

Some notes on variables used to time music:
- `Pose2PStart_Frames` is incremented, and is -1 while inactive
- `Pose2PStart_Frames_SkyRailMetalHarbor` is decremented, and is 0 while inactive

**Comment by SonicFreak94** [comment]
After some testing, it's almost certainly action and not game state synchronization.

**Comment by michael-fadely** [comment]
The solution to this was forcing both players' actions to 0 as the object is deleted so that the BgmStart object doesn't get confused.
