### ISSUE TITLE
PLS help

### ISSUE THREAD

**Issue by CSS655** [SonicFreak94/sa2-battle-network#37]
Me & a friend of mine did everything like right we didnt get errors or anything but it still doesnt work i want to ask if we are missing something like a prompt or something if you have machi for example what do you exactly do , for example is it only beeing in the same server that is enough our is it doing something extra here i'll show you http://puu.sh/sWZtP/2c14ced0d4.png . if you have any idea pls help up he looked it all up & apperantly we did nothing wrong

**Comment by michael-fadely** [comment]
Read the instructions more carefully. You put the command-line arguments in the wrong place entirely.

**Comment by CSS655** [comment]
where are there suppose to go then if you pls if thats the wrong place? because we thought it was suppose to be in the name & target

**Comment by michael-fadely** [comment]
http://forums.sonicretro.org/index.php?showtopic=31932
